Meal wrapper
rebecka-oscarsson/lollipop pull request #52
Opened 2021-12-22 13:26 UTC by Sarasedaghat8960

Meal Wrapper for mobile view

2021-12-22 13:34 UTC, EmilNilsson12 requested changes
Vad är ändrat i Menu.module.scss?

2021-12-22 14:11 UTC, EmilNilsson12 approved these changes
Snyggt med prettier!

2021-12-22 14:11 UTC, EmilNilsson12 commented on src/components/Menu/Menu.module.scss
> +    z-index: 1;
Ser bra ut nu!

2021-12-22 14:13 UTC, rebecka-oscarsson approved these changes
Snyggt!

Kanske kan vara <section> för mealWrapper och <figure> på mealcard och <figcaption> på texten om maträtten? Istället för <div>, för att det ska bli mer semantisk html.

Tänkte också på att det inte behövs tre olika klasser för korten, om ett av dem ska vara annorlunda kan man lägga till en extra klass i det istället. Men det är ju en småsak så det kan du strunta i.

2021-12-22 14:26 UTC, EmilNilsson12 requested changes
Hittade en del saker som såg lite skumt ut

2021-12-22 14:26 UTC, EmilNilsson12 commented on src/components/MealWrapper/MealWrapper.jsx
> +            <h1 className={styles.MealwrapparHeader}>FAVORITER</h1>
Denna borde vara h2, enda h1 vi har är "Grand Opening" på landing page

2021-12-22 14:26 UTC, EmilNilsson12 commented on src/components/MealWrapper/MealWrapper.jsx
> +                    <h2 className={styles.MealCardPris1}>120 kr</h2>
Dessa borde inte vara h2, enligt design-assets borde de vara lika stora som h2, men h2 i MealCardContainer borde vara namnet på måltiden.
Kanske kan vara en p-tag?

2021-12-22 16:53 UTC, postmodernistx commented on src/components/CookieBanner/CookieBanner.jsx
> +import styles from './CookieBanner.module.scss'
I think you should keep the semicolon at the end, as it allows for fewer mistakes in JavaScript :) But it's a style choice, so whichever works just fine technically!

2021-12-22 16:53 UTC, postmodernistx commented on src/components/Footer/Footer.jsx
> +            <div className={styles.NewsLetter}>NewsLetter</div>
Casing on "NewsLetter" should probably be → "Newsletter" (lowercase "L")?

2021-12-22 16:54 UTC, postmodernistx commented on src/components/LandingPage/LandingPage.jsx
> +            <picture>
Great use of the picture tag and media queries!

2021-12-22 16:55 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +            <h2 className={styles.MealwrapparHeader}>FAVORITER</h2>
Uppercase styling could be handled in CSS.

2021-12-22 16:55 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        alt="pic"
This is not a great alt text :) Consider something more descriptive or leave empty, if irrelevant. I.e. `<img alt="">`

2021-12-22 16:56 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                    <h3 className={styles.MealCardHeade}>OHANA BOWL</h3>
Could also be uppercased through CSS :)

2021-12-22 16:56 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        Ris,lax,gurka,edamame,böner,mango
Spelling: "böner" → "bönor"
Also add space after the commas :)

2021-12-22 16:57 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        Toppad med chilimajnäs.
"Chilimajnäs" → "Chilimajonnäs"

2021-12-22 16:57 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        alt="pic"
Check also this alt text :)

2021-12-22 16:57 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        alt="pic"
And other similar alt texts, double-check those :)

2021-12-22 17:00 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        Ris,lax,gurka,edamame,böner,mango
Spaces between commas here as well, and "böner" → "bönor".

2021-12-22 17:00 UTC, postmodernistx commented on src/components/MealWrapper/MealWrapper.jsx
> +                        Toppad med chilimajnäs.
Spelling also here :)

2021-12-22 17:00 UTC, postmodernistx approved these changes
Great! Quite a large PR with many files to review, so consider a smaller pull request, if possible. Sometimes a new feature or change requires a lot of files, of course.

Some of the photos are quite large, i.e. "foodPhoto.jpg" is 4.76 MB. Does it need to be in version control at that size?

Super with prettier, very good for constiency in the code style! 👍

2021-12-22 18:26 UTC, EmilNilsson12 approved these changes

2021-12-22 21:32 UTC, merged

2021-12-23 08:21 UTC, postmodernistx reviewed
Great!